import puppeteer from 'puppeteer-core'
const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox', '--disable-gpu'] })
const errors = []
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const page = await browser.newPage()
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
page.on('pageerror', (e) => errors.push(e.message))
await page.setViewport({ width: 1440, height: 900 })
await page.goto('http://localhost:4919/', { waitUntil: 'networkidle0' })
await page.evaluate(() => localStorage.clear())
await page.reload({ waitUntil: 'networkidle0' })
await sleep(2800)
const about = await page.$('button.dicon[aria-label="Open About Mikail"]')
const ab = await about.boundingBox()
await page.mouse.click(ab.x + ab.width / 2, ab.y + ab.height / 2, { clickCount: 2 })
await sleep(500)
await page.click('[data-dock="hackathons"]'); await sleep(500)
// marquee select
await page.mouse.move(600, 200); await page.mouse.down(); await page.mouse.move(60, 700, { steps: 10 }); await sleep(100)
await page.screenshot({ path: '.smoke/r1-about-marquee.png' })
await page.mouse.up()
// zoom hackathons
await page.click('.win.focused .traffic .max'); await sleep(500)
await page.screenshot({ path: '.smoke/r2-zoom.png' })
console.log('wins', await page.$$eval('.win', (els) => els.map((e) => e.className)))
const m = await browser.newPage()
m.on('pageerror', (e) => errors.push('m ' + e.message))
await m.setViewport({ width: 390, height: 844, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
await m.goto('http://localhost:4919/', { waitUntil: 'networkidle0' }); await sleep(2800)
const icons = await m.$$('.m-grid .m-icon'); await icons[1].tap(); await sleep(600)
await m.screenshot({ path: '.smoke/r3-m-writing.png' })
await icons[5] // terminal is hidden under sheet; use minimize then tap
await m.tap('.sheet-head .ib'); await sleep(500)
const icons2 = await m.$$('.m-grid .m-icon'); await icons2[5].tap(); await sleep(700)
await m.type('.sheet input', 'neofetch'); await m.keyboard.press('Enter'); await sleep(300)
await m.screenshot({ path: '.smoke/r4-m-terminal.png' })
console.log('ERRORS', errors.length ? errors.join('\n') : 'none')
await browser.close()
