import { useEffect, useRef, useState } from 'react';
import { Search, Wifi, BatteryFull, Volume2, ChevronRight, ArrowUpRight, Check, X, Minus, Maximize2, PanelLeft, Command, Sun, Moon, Monitor, ArrowRight, Grid2X2 } from './ui-icons';
import { apps, AppIcon, type AppId } from './icons';
import { About, Hackathons, Writing, Lab, Papers, Trash } from './Content';
type Win = {id:AppId;x:number;y:number;z:number;minimized:boolean;maximized:boolean};
type Menu = 'system'|'file'|'view'|'window'|'help'|'settings'|null;
const initialWindow = ():Win => ({id:'about',x:Math.max(170,Math.min(window.innerWidth*.205,window.innerWidth-865)),y:Math.max(62,Math.min(94,window.innerHeight*.105)),z:1,minimized:false,maximized:false});

function Wallpaper({theme}:{theme:string}) {return <div className={`wallpaper ${theme}`} aria-hidden="true"><svg viewBox="0 0 1600 1000" preserveAspectRatio="xMidYMid slice"><defs><pattern id="grain" width="6" height="6" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".45" fill="#293623" opacity=".13"/><circle cx="4" cy="4" r=".4" fill="#293623" opacity=".08"/></pattern><radialGradient id="light"><stop stopColor="#f3f0df"/><stop offset="1" stopColor="#e4e7d7"/></radialGradient></defs><rect width="1600" height="1000" fill="url(#light)"/><circle cx="1325" cy="315" r="167" fill="#e7c394" opacity=".65"/><path d="M-150 1020C45 587 424 913 785 720S1161 338 1758 499V1100Z" fill="#c3cbb0"/><path d="M-100 1020C197 710 425 964 851 766s510-352 906-175v460Z" fill="#acb895"/>{Array.from({length:13},(_,i)=><path key={i} d={`M-100 ${830+i*28}C220 ${583+i*31} 419 ${987+i*17} 861 ${709+i*23}S1300 ${459+i*22} 1770 ${601+i*27}`} stroke="#788964" strokeWidth="1" opacity=".31" fill="none"/>)}<path d="M-70 1140C342 758 598 1155 1107 862s466-254 696-233v500Z" fill="#859572" opacity=".6"/><rect width="1600" height="1000" fill="url(#grain)"/></svg><div className="wallpaper-type">Stay curious.<br/><em>Make things.</em><span>A LITTLE CORNER OF THE INTERNET, BY MIKAIL.</span></div><div className="wallpaper-coordinate">PERSONAL SPACE / PUBLIC INTERNET<br/>43°39′ N &nbsp; 79°23′ W</div></div>}
function ClockWidget({now}:{now:Date}) {const hours=now.getHours()%12;return <div className="clock-widget"><div className="analog-clock"><div className="clock-face">{Array.from({length:12},(_,i)=><i key={i} style={{transform:`rotate(${i*30}deg)`}}/>)}<span className="hour-hand" style={{transform:`rotate(${hours*30+now.getMinutes()*.5}deg)`}}/><span className="minute-hand" style={{transform:`rotate(${now.getMinutes()*6}deg)`}}/><span className="second-hand" style={{transform:`rotate(${now.getSeconds()*6}deg)`}}/><b/></div></div><span>{now.toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})}</span><small>A good day to make something.</small></div>}

export default function App(){
 const [windows,setWindows]=useState<Win[]>(() => [initialWindow()]);
 const topZ=useRef(1);const [now,setNow]=useState(new Date());const [menu,setMenu]=useState<Menu>(null);
 const [search,setSearch]=useState(false);const [query,setQuery]=useState('');const [help,setHelp]=useState(false);
 const [theme,setTheme]=useState('day');const [showWidgets,setShowWidgets]=useState(true);const [toast,setToast]=useState('');
 const [selected,setSelected]=useState<AppId|null>(null);const [noteDone,setNoteDone]=useState(false);
 const drag=useRef<{id:AppId;dx:number;dy:number}|null>(null);const searchInput=useRef<HTMLInputElement>(null);
 const visible=windows.filter(w=>!w.minimized);const active=visible.reduce<Win|undefined>((a,b)=>!a||b.z>a.z?b:a,undefined);
 function focus(id:AppId){setWindows(ws=>ws.map(w=>w.id===id?{...w,z:++topZ.current}:w));}
 function open(id:AppId){setWindows(ws=>{const exists=ws.find(w=>w.id===id);if(exists)return ws.map(w=>w.id===id?{...w,minimized:false,z:++topZ.current}:w);const offset=(ws.length%4)*24;return [...ws,{id,x:Math.max(150,Math.min(window.innerWidth*.205+offset,window.innerWidth-865)),y:74+offset,z:++topZ.current,minimized:false,maximized:false}];});setMenu(null);setSearch(false);setQuery('');}
 function close(id:AppId){setWindows(ws=>ws.filter(w=>w.id!==id));}
 function minimize(id:AppId){setWindows(ws=>ws.map(w=>w.id===id?{...w,minimized:true}:w));}
 function maximize(id:AppId){setWindows(ws=>ws.map(w=>w.id===id?{...w,maximized:!w.maximized,z:++topZ.current}:w));}
 function notify(message:string){setToast(message);}
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{
   if (!search && !help) return;
   const previous = document.activeElement as HTMLElement | null;
   const panel = document.querySelector<HTMLElement>('.overlay [role="dialog"]');
   const focusable = () => Array.from(panel?.querySelectorAll<HTMLElement>('button, input, a[href], [tabindex="0"]') ?? []).filter(el => !el.hasAttribute('disabled'));
   (search ? searchInput.current : focusable()[0])?.focus();
   const trap = (event: KeyboardEvent) => {
     if (event.key !== 'Tab') return;
     const elements = focusable();
     const first = elements[0], last = elements[elements.length - 1];
     if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
     else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
   };
   document.addEventListener('keydown', trap);
   return () => { document.removeEventListener('keydown', trap); previous?.focus(); };
 },[search, help]);
 useEffect(()=>{function key(e:KeyboardEvent){const typing=e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(s=>!s);setMenu(null);}else if((e.metaKey||e.ctrlKey)&&/^[1-6]$/.test(e.key)){e.preventDefault();open(apps[Number(e.key)-1].id);}else if(e.key==='Escape'){if(search)setSearch(false);else if(help)setHelp(false);else if(menu)setMenu(null);else if(active)close(active.id);}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='w'){e.preventDefault();if(active)close(active.id);}else if(e.altKey&&e.key==='Tab'){e.preventDefault();const sorted=visible.sort((a,b)=>a.z-b.z);if(sorted.length)focus(sorted[0].id);}else if(!typing&&e.key==='?' ){setHelp(true);}else if(!typing&&e.key==='Enter'&&selected){open(selected);}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 useEffect(()=>{function move(e:PointerEvent){if(!drag.current)return;const {id,dx,dy}=drag.current;setWindows(ws=>ws.map(w=>w.id===id?{...w,x:Math.max(-600,Math.min(window.innerWidth-100,e.clientX-dx)),y:Math.max(36,Math.min(window.innerHeight-140,e.clientY-dy))}:w));}function end(){drag.current=null;document.body.classList.remove('dragging');}window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',end);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',end);};},[]);
 const toggleMenu=(value:Menu)=>setMenu(menu===value?null:value);
 const menuAction=(fn:()=>void)=>{fn();setMenu(null);};
 return <main className={`os ${theme}`}>
  <Wallpaper theme={theme}/>
  <header className="menubar"><div className="menu-left"><button className={`system-button ${menu==='system'?'menu-active':''}`} onClick={()=>toggleMenu('system')} aria-label="System menu"><span className="system-mark">m<span>✳</span></span></button><b className="os-name">mikailOS</b>{(['file','view','window','help'] as const).map(m=><button key={m} className={`menu-button ${menu===m?'menu-active':''}`} onClick={()=>toggleMenu(m)}>{m[0].toUpperCase()+m.slice(1)}</button>)}</div><div className="menu-right"><span className="menu-welcome">Make yourself at home.</span><button className="top-icon" aria-label="Search desktop" onClick={()=>{setSearch(true);setMenu(null);}}><Search size={15}/></button><button className="system-status" aria-label="Open desktop settings" onClick={()=>toggleMenu('settings')}><Wifi size={15}/><Volume2 size={15}/><BatteryFull size={21}/></button><span className="system-time">{now.toLocaleDateString('en-US',{weekday:'short'})} {now.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</span></div></header>
  {menu&&<><div className="menu-dismiss" onClick={()=>setMenu(null)}/><div className={`dropdown-menu menu-${menu}`}>
    {menu==='system'&&<><div className="dropdown-heading">mikailOS <span>v. 1.0</span></div><button onClick={()=>menuAction(()=>open('about'))}>About this human <ArrowUpRight size={14}/></button><button onClick={()=>menuAction(()=>{setWindows([initialWindow()]);topZ.current=1;notify('A fresh start. Welcome home.');})}>Restart desktop <span>↻</span></button><div className="menu-caption">Made with curiosity, since 2002.</div></>}
    {menu==='file'&&<><button onClick={()=>menuAction(()=>setSearch(true))}>Open application… <kbd>⌘ K</kbd></button><button disabled={!active} onClick={()=>menuAction(()=>{if(active)close(active.id);})}>Close window <kbd>⌘ W</kbd></button></>}
    {menu==='view'&&<><button onClick={()=>menuAction(()=>setWindows(ws=>ws.map(w=>({...w,minimized:true}))))}>Show desktop <Monitor size={14}/></button><button onClick={()=>menuAction(()=>setShowWidgets(v=>!v))}>Desktop widgets {showWidgets&&<Check size={14}/>}</button><button onClick={()=>menuAction(()=>setTheme(t=>t==='day'?'dusk':'day'))}>Switch to {theme==='day'?'dusk':'daylight'} {theme==='day'?<Moon size={14}/>:<Sun size={14}/>}</button></>}
    {menu==='window'&&<>{windows.length===0?<div className="menu-caption">No open windows</div>:windows.map(w=><button key={w.id} onClick={()=>open(w.id)}>{apps.find(a=>a.id===w.id)?.title}{w.id===active?.id?<Check size={14}/>:w.minimized?<Minus size={14}/>:null}</button>)}<button onClick={()=>menuAction(()=>setWindows(ws=>ws.map((w,i)=>({...w,x:190+(i%5)*28,y:70+(i%5)*28,maximized:false,minimized:false}))))}>Arrange windows <Grid2X2 size={14}/></button></>}
    {menu==='help'&&<><button onClick={()=>menuAction(()=>setHelp(true))}>Keyboard shortcuts <Command size={14}/></button><button onClick={()=>menuAction(()=>notify('Double-click a desktop icon, or use the dock. Make yourself at home.'))}>A little tour <ArrowUpRight size={14}/></button></>}
    {menu==='settings'&&<><div className="dropdown-heading">Control center <Sun size={15}/></div><div className="settings-status"><Wifi size={17}/><div><b>Offline friendly</b><small>Everything is right here.</small></div><span className="status-dot"/></div><div className="section-label"><span>WALLPAPER</span></div><div className="theme-options"><button className={theme==='day'?'chosen':''} onClick={()=>setTheme('day')}><Sun size={21}/>Daylight</button><button className={theme==='dusk'?'chosen':''} onClick={()=>setTheme('dusk')}><Moon size={21}/>Dusk</button></div><button onClick={()=>setShowWidgets(v=>!v)}>Show desktop widgets {showWidgets&&<Check size={14}/>}</button></>}
  </div></>}
  <section className="desktop-icons" aria-label="Desktop applications">{apps.map(app=><button key={app.id} className={`desktop-icon ${selected===app.id?'selected':''}`} onClick={()=>{setSelected(app.id);if(window.matchMedia('(pointer: coarse)').matches)open(app.id);}} onDoubleClick={()=>open(app.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(app.id);}}} aria-label={`Open ${app.title}`}><AppIcon id={app.id}/><span>{app.title}</span>{app.id==='about'&&<small>start here ↗</small>}</button>)}</section>
  {showWidgets&&<aside className="desktop-widgets"><ClockWidget now={now}/><div className="sticky-note"><span className="tape"/><div className="note-heading">A NOTE TO MYSELF <span>↗</span></div><p>Make useful things.<br/>Make useless things.<br/><em>Just keep making.</em></p><button onClick={()=>setNoteDone(!noteDone)} className={noteDone?'done':''}><span>{noteDone&&<Check size={12}/>}</span>{noteDone?'You’re doing the thing.':'Enjoy the process.'}</button><div className="note-sign">— m.</div></div></aside>}
  <div className="desktop-hint"><span className="status-dot"/> Somewhere between building & becoming.</div><div className="desktop-build">PERSONAL OS <span>© 2026</span></div>
  <section className="windows" aria-label="Open application windows">{windows.map(w=><section key={w.id} role="dialog" aria-label={apps.find(a=>a.id===w.id)?.title} hidden={w.minimized} className={`app-window ${w.maximized?'maximized':''} ${active?.id===w.id?'focused':''}`} style={{left:w.x,top:w.y,zIndex:10+w.z}} onPointerDown={()=>{if(active?.id!==w.id)focus(w.id);}}>
   <div className="window-titlebar" onDoubleClick={()=>maximize(w.id)} onPointerDown={e=>{if((e.target as HTMLElement).closest('button')||w.maximized||window.innerWidth<=700)return;drag.current={id:w.id,dx:e.clientX-w.x,dy:e.clientY-w.y};e.currentTarget.setPointerCapture(e.pointerId);document.body.classList.add('dragging');}}><div className="window-controls"><button className="control close" aria-label={`Close ${apps.find(a=>a.id===w.id)?.title}`} onClick={()=>close(w.id)}><X size={9}/></button><button className="control minimize" aria-label="Minimize window" onClick={()=>minimize(w.id)}><Minus size={9}/></button><button className="control maximize" aria-label="Maximize window" onClick={()=>maximize(w.id)}><Maximize2 size={8}/></button></div><span className="window-title"><AppIcon id={w.id}/>{apps.find(a=>a.id===w.id)?.title}</span><button className="window-search" aria-label="Search applications" onClick={()=>setSearch(true)}><Search size={14}/></button></div>
   <div className="window-layout"><nav className="window-sidebar"><div className="sidebar-heading">MY LITTLE WORLD</div>{apps.filter(a=>a.id!=='trash').map(a=><button key={a.id} className={a.id===w.id?'active':''} onClick={()=>open(a.id)}><AppIcon id={a.id}/>{a.title}{a.id===w.id&&<span>●</span>}</button>)}<div className="sidebar-bottom"><div className="sidebar-flower">✳</div><p>Always a<br/>work in progress.</p><span>LAST TENDED TO<br/>SEPTEMBER 2026</span></div></nav><div className="window-main"><div className="breadcrumb"><PanelLeft size={14}/><span>mikail</span><ChevronRight size={12}/><b>{w.id==='about'?'hello.md':apps.find(a=>a.id===w.id)?.title.toLowerCase()}</b><span className="breadcrumb-end">{w.id==='about'?'⌘ 1':'⌘ '+(apps.findIndex(a=>a.id===w.id)+1)}</span></div><div className="window-scroll">{w.id==='about'?<About open={open}/>:w.id==='hackathons'?<Hackathons/>:w.id==='writing'?<Writing/>:w.id==='lab'?<Lab/>:w.id==='papers'?<Papers/>:<Trash/>}</div></div></div><footer className="window-footer"><span><span className="status-dot"/> {w.id==='about'?'A little introduction':apps.find(a=>a.id===w.id)?.sub}</span><span>Made of pixels & possibility <span>↗</span></span></footer>
  </section>)}</section>
  <nav className="dock" aria-label="Application dock">{apps.filter(a=>a.id!=='trash').map(a=><button key={a.id} className={`dock-item ${active?.id===a.id?'active':''}`} aria-label={`Open ${a.title}`} onClick={()=>{if(active?.id===a.id)minimize(a.id);else open(a.id);}}><span className="dock-tooltip">{a.title}</span><AppIcon id={a.id}/><i className={windows.some(w=>w.id===a.id)?'running':''}/></button>)}<span className="dock-divider"/><button className="dock-item" aria-label="Desktop settings" onClick={()=>toggleMenu('settings')}><span className="dock-tooltip">Settings</span><AppIcon id="settings"/><i/></button><button className="dock-item" aria-label="Open Trash" onClick={()=>open('trash')}><span className="dock-tooltip">Trash</span><AppIcon id="trash"/><i className={windows.some(w=>w.id==='trash')?'running':''}/></button></nav>
  {search&&<div className="overlay" onPointerDown={e=>{if(e.target===e.currentTarget)setSearch(false);}}><section className="spotlight" role="dialog" aria-modal="true" aria-label="Search desktop"><div className="search-input"><Search size={22}/><input ref={searchInput} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a little something…" onKeyDown={e=>{if(e.key==='Enter'){const first=apps.find(a=>(a.title+' '+a.sub).toLowerCase().includes(query.toLowerCase()));if(first)open(first.id);}}}/><button onClick={()=>setSearch(false)} aria-label="Close search"><kbd>esc</kbd></button></div><div className="search-results"><div className="section-label">{query?'RESULTS':'EXPLORE THIS DESKTOP'}</div>{apps.filter(a=>(a.title+' '+a.sub).toLowerCase().includes(query.toLowerCase())).map(a=><button key={a.id} onClick={()=>open(a.id)}><AppIcon id={a.id}/><span><b>{a.title}</b><small>{a.sub}</small></span><ArrowUpRight size={16}/></button>)}{!apps.some(a=>(a.title+' '+a.sub).toLowerCase().includes(query.toLowerCase()))&&<p className="no-results">Nothing here by that name. Try “writing” or “lab”.</p>}</div><footer><span>Type to explore</span><span>↵ to open</span></footer></section></div>}
  {help&&<div className="overlay" onClick={e=>{if(e.target===e.currentTarget)setHelp(false);}}><section className="help-panel" role="dialog" aria-modal="true" aria-label="Welcome and keyboard shortcuts"><button className="help-close icon-button" aria-label="Close help" onClick={()=>setHelp(false)}><X size={18}/></button><span className="help-flower">✳</span><h2>Make yourself at home.</h2><p>This is a small, explorable corner of the internet.<br/>Double-click an icon. Open a window. Stay a while.</p><div className="shortcut-row"><span>Find something</span><kbd>⌘ / Ctrl K</kbd></div><div className="shortcut-row"><span>Close the active window</span><kbd>Esc / ⌘ W</kbd></div><div className="shortcut-row"><span>Cycle windows</span><kbd>Alt Tab</kbd></div><div className="shortcut-row"><span>Show this little guide</span><kbd>?</kbd></div><p className="help-tip">Drag a title bar to move a window. Double-click it to maximize. On touch screens, just tap an app.</p><button className="primary-button" onClick={()=>setHelp(false)}>Got it, let’s explore <ArrowRight size={14}/></button></section></div>}
  {toast&&<div role="status" className="toast"><Check size={16}/>{toast}</div>}
  <button className="mobile-home" onClick={()=>setWindows(ws=>ws.map(w=>({...w,minimized:true})))} aria-label="Show home screen"><span/></button>
 </main>
}
