import { useState } from 'react';
import { ArrowUpRight, ArrowLeft, ArrowRight, Check, Copy, Sparkles, RotateCcw, Trash2, Play, Pause, Plus } from './ui-icons';
import { AppIcon, ComputerArt, type AppId } from './icons';

export function About({ open }: { open: (id: AppId) => void }) {
 const [contact, setContact] = useState(false);
 const [copied, setCopied] = useState(false);
 return <div className="about-page">
   <div className="eyebrow"><span className="tiny-star">✳</span> A HUMAN BEHIND THE PIXELS</div>
   <div className="intro"><div><h1>Hi, I’m <em>Mikail.</em></h1><p className="intro-line">Front-end engineer.<br/>Endlessly curious person.</p></div><ComputerArt/></div>
   <p className="bio">I turn ideas into things you can click, feel, and get a little<br className="desktop-break"/> lost in. Drawn to thoughtful interfaces, playful experiments,<br className="desktop-break"/> and the details that make software feel human.</p>
   <div className="about-actions"><button className="primary-button" onClick={()=>setContact(!contact)}>Let’s talk <ArrowUpRight size={15}/></button><span className="availability"><i/> Open to good conversations</span></div>
   {contact && <div className="contact-panel"><div><b>A good place to start.</b><a href="mailto:hello@mikail.example">hello@mikail.example <ArrowUpRight size={12}/></a><small>Demo contact · replace with your address</small></div><button className="icon-button" aria-label="Copy email address" onClick={async()=>{try {await navigator.clipboard.writeText('hello@mikail.example');setCopied(true);}catch{setCopied(false);}}}>{copied ? <Check size={16}/> : <Copy size={16}/>}</button></div>}
   <div className="section-label"><span>CURRENTLY ON MY DESK</span><span>03 ITEMS</span></div>
   <div className="desk-links">
    <button onClick={()=>open('hackathons')}><span className="mini-tile olive"><AppIcon id="hackathons"/></span><span><b>Making things in 48 hours</b><small>Hackathons, late nights & a few wins</small></span><ArrowUpRight size={17}/></button>
    <button onClick={()=>open('writing')}><span className="mini-tile apricot"><AppIcon id="writing"/></span><span><b>A place to think out loud</b><small>Notes on the web and everything around it</small></span><ArrowUpRight size={17}/></button>
    <button onClick={()=>open('lab')}><span className="mini-tile lavender"><AppIcon id="lab"/></span><span><b>Delight is in the details</b><small>A collection of tiny, slightly unnecessary things</small></span><ArrowUpRight size={17}/></button>
   </div>
   <div className="about-foot"><span>Built with care. And probably too much coffee.</span><span>☺</span></div>
 </div>
}
const projects = [
 {name:'Common Ground',type:'01 / CIVIC TECH', date:'OCT 2025', prize:'1st place', tag:'Hack the North', color:'green',desc:'A little less scrolling. A lot more community.', detail:'An accessible neighborhood map that turns spare time into local volunteering. We built location search, an event matching flow, and a beautifully simple way to show up for your neighbors.',stack:['React','Mapbox','Supabase'],symbol:'✳'},
 {name:'Afterhours',type:'02 / CREATIVE TOOLS',date:'AUG 2025',prize:'Best design',tag:'Buildspace Weekend',color:'orange',desc:'A shared room for people making things.',detail:'A cozy virtual studio for independent makers. Ambient presence, collaborative sketches, and timed focus sessions make working alone feel a little less lonely.',stack:['Next.js','WebSockets','Canvas'],symbol:'✺'},
 {name:'Second Nature',type:'03 / SUSTAINABILITY',date:'MAR 2025',prize:'Finalist',tag:'Hack for Tomorrow',color:'blue',desc:'Small everyday choices, made visible.',detail:'A playful receipt scanner that makes the environmental footprint of a grocery shop understandable. I led the interface, data visualizations, and the prototype presentation.',stack:['TypeScript','D3.js','Python'],symbol:'❋'},
];
export function Hackathons(){
 const [selected,setSelected] = useState<number|null>(null);
 return <div className="content-page"><div className="eyebrow">IDEA → COFFEE → SHIP</div><h1>Built in a <em>weekend.</em></h1><p className="page-description">Good people, unreasonable deadlines, and ideas worth losing sleep over.</p><div className="stats-strip"><div><b>08</b><span>HACKATHONS</span></div><div><b>03</b><span>LITTLE WINS</span></div><div><b>∞</b><span>THINGS LEARNED</span></div></div><div className="project-list">{projects.map((p,i)=><button className={`project-card ${selected === i ? 'expanded':''}`} key={p.name} onClick={()=>setSelected(selected===i?null:i)} aria-expanded={selected===i}><div className={`project-visual ${p.color}`}><span>{p.symbol}</span><small>{p.type}</small><div className="prize">↗ {p.prize}</div></div><div className="project-copy"><div className="project-meta">{p.tag}<span>{p.date}</span></div><h2>{p.name}<ArrowUpRight size={19}/></h2><p>{p.desc}</p>{selected===i&&<div className="project-detail"><p>{p.detail}</p><div className="tag-list">{p.stack.map(s=><span key={s}>{s}</span>)}</div><small>Prototype case study · Front-end & interaction design</small></div>}</div></button>)}</div><p className="muted-note">Sample projects from an imaginary, very productive year.</p></div>
}
const essays = [
 {title:'The web could use a little more weird',subtitle:'In defense of personal websites that feel personal.',date:'NOV 12, 2025',read:'4 MIN',category:'THE INTERNET',body:["I miss stumbling onto a website and feeling like I’ve wandered into someone’s room. A strange cursor. A guestbook. A button that does absolutely nothing useful, but makes you smile.","We’ve gotten very good at making the internet efficient. We know where the call to action goes. We know how to shave a fraction of a second off a page load. But somewhere between the design systems and the conversion funnels, we sometimes forget that the web is also a place to play.","A personal website is a small opportunity to make something that doesn’t need to scale. It can be unfinished. It can contain an odd little experiment. It can make a visitor pause, explore, or wonder how something was built.","That’s why this site is a desktop. It’s a tiny space to move things around, open a drawer, and find something unexpected. A little less polished pitch. A little more person.","Make your corner of the internet feel like you live there."]},
 {title:'Good motion knows when to get out of the way',subtitle:'A few thoughts on interfaces that feel quietly alive.',date:'OCT 03, 2025',read:'6 MIN',category:'INTERACTION',body:["The best animation is often the one you only notice when it’s gone. The drawer that keeps pace with your hand. The button that seems to understand the weight of a click.","I like to think about motion as a sentence. It should have a beginning, a little momentum, and a clear ending. Too many exclamation marks and the interface becomes exhausting.","Start with the relationship between two states. Where was this element? Where is it going? A short transition can answer those questions more naturally than any label.","Then test the experience with every animation turned off. Respect reduced-motion preferences. If the interface stops making sense, the motion is doing work that structure should be doing.","A good rule: animate to explain, then remove half of what’s left."]},
 {title:'A field guide to finishing side projects',subtitle:'Making the last ten percent feel a little smaller.',date:'SEP 18, 2025',read:'5 MIN',category:'MAKING',body:["My side-project folder used to be a museum of promising first weekends. Lovely beginnings. Very few endings.","What changed was writing down the smallest interesting version of an idea before opening the editor. Not the minimum viable business. Just the smallest version I’d be happy to send to a friend.","A project can be complete without being comprehensive. One interaction done with care can say more than ten unfinished features.","Leave yourself a note at the end of each session. Tomorrow’s first step should already be waiting for you. And when it feels ready, share it. The next idea will be there when you come back."]},
];
export function Writing(){const [article,setArticle] = useState<number|null>(null);return <div className="content-page writing-page">{article===null?<><div className="eyebrow">OCCASIONAL WORDS, NO CONTENT CALENDAR</div><h1>Notes to <em>self.</em></h1><p className="page-description">About making things, noticing things, and figuring it out.</p><div className="writing-feature"><span>THE LATEST ENTRY</span><span className="writing-doodle">a a<span>↗</span></span><h2>{essays[0].title}</h2><p>{essays[0].subtitle}</p><button onClick={()=>setArticle(0)}>Read the note <ArrowRight size={15}/></button></div><div className="section-label"><span>ALL NOTES</span><span>2025</span></div>{essays.map((a,i)=><button className="essay-row" key={a.title} onClick={()=>setArticle(i)}><span className="essay-number">0{i+1}</span><span><small>{a.category} · {a.read}</small><h3>{a.title}</h3><p>{a.date}</p></span><ArrowUpRight size={18}/></button>)}</>:<article><button className="back-link" onClick={()=>setArticle(null)}><ArrowLeft size={14}/> All notes</button><div className="eyebrow">{essays[article].category} · {essays[article].read} READ</div><h1>{essays[article].title}</h1><p className="article-date">Mikail · {essays[article].date}</p>{essays[article].body.map(p=><p className="article-p" key={p}>{p}</p>)}<div className="article-end">✳<span>Thanks for stopping by.</span></div></article>}</div>}
export function Lab(){const [running,setRunning] = useState(true);const [speed,setSpeed] = useState(5);const [color,setColor] = useState('olive');const [count,setCount] = useState(0);return <div className="content-page"><div className="eyebrow"><Sparkles size={12}/> NO PRACTICAL PURPOSE REQUIRED</div><h1>A little <em>what if?</em></h1><p className="page-description">An evolving shelf of experiments. Touch things. See what happens.</p><div className="lab-experiment"><div className="experiment-header"><span><i/> EXPERIMENT 001</span><span>LIVE CANVAS</span></div><div className={`orbit-playground ${color}`} style={{'--speed':`${11-speed}s`,'--play':running?'running':'paused'} as React.CSSProperties}><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-ring ring-three"/><div className="orbit-center">✳</div><span className="orbit-caption">everything, in its own time.</span></div><div className="experiment-controls"><button className="icon-button" aria-label={running?'Pause animation':'Play animation'} onClick={()=>setRunning(!running)}>{running?<Pause size={16}/>:<Play size={16}/>}</button><label>Tempo <input aria-label="Orbit tempo" type="range" min="1" max="10" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label><div className="swatches">{['olive','rust','blue'].map(c=><button key={c} className={`swatch ${c} ${c===color?'selected':''}`} aria-label={`${c} palette`} aria-pressed={c===color} onClick={()=>setColor(c)}/>)}</div></div></div><div className="lab-title"><h2>Orbital daydream</h2><span>CSS · MOTION STUDY</span></div><p className="lab-desc">Three circles, a little patience, and a reminder that not everything needs to get somewhere.</p><button className="click-experiment" onClick={()=>setCount(count+1)}><span className="click-flower" style={{transform:`rotate(${count*30}deg)`}}>✺</span><span><b>A very satisfying button</b><small>{count===0?'Click for absolutely no reason.':`${count} little moment${count===1?'':'s'} of delight. Keep going.`}</small></span><Plus size={20}/></button></div>}
export function Papers(){const [expanded,setExpanded] = useState<number|null>(null);return <div className="content-page"><div className="eyebrow">FROM THE READING PILE</div><h1>Slower <em>thinking.</em></h1><p className="page-description">Research notes, rabbit holes, and ideas I’m still working through.</p>{[{title:'The perception of speed',desc:'Why an interface can feel fast even when it isn’t.',tag:'HUMAN–COMPUTER INTERACTION',note:'A review of perceived performance patterns: optimistic updates, skeleton screens, and progress feedback. The working hypothesis: predictability matters just as much as raw speed. A stable layout and immediate acknowledgement can make waiting feel shorter.',date:'October 2025',pages:'8 pages'},{title:'Small interfaces, big feelings',desc:'An analysis of emotional design in everyday tools.',tag:'DESIGN ANALYSIS',note:'Looking at how small details create attachment to software. This analysis groups examples into three themes: recognizable material, gentle surprises, and a sense of ownership. Personalization is most effective when it helps people leave a trace of themselves.',date:'September 2025',pages:'12 pages'},{title:'A more accessible canvas',desc:'Notes on building beyond the DOM without leaving people out.',tag:'ENGINEERING NOTES',note:'A practical checklist for canvas experiments: provide equivalent HTML controls, describe the current state in text, expose keyboard interactions, and pause nonessential motion. Accessibility belongs in the sketch, not just in the final review.',date:'July 2025',pages:'6 pages'}].map((p,i)=><button className="paper-card" key={p.title} onClick={()=>setExpanded(expanded===i?null:i)} aria-expanded={expanded===i}><span className="paper-index">[0{i+1}]</span><div><div className="eyebrow">{p.tag}</div><h2>{p.title}</h2><p>{p.desc}</p><small>{p.date} · {p.pages} · Working draft</small>{expanded===i&&<div className="paper-abstract"><b>Abstract / reading note</b><p>{p.note}</p><span>Sample research note for this prototype.</span></div>}</div><Plus size={17} style={{transform:expanded===i?'rotate(45deg)':''}}/></button>)}<div className="research-note">↳ Thinking in public. These are notes, not final answers.</div></div>}
export function Trash(){const [empty,setEmpty]=useState(false);return <div className="content-page"><div className="eyebrow">THE ART OF LETTING GO</div><h1>Room for <em>better.</em></h1><p className="page-description">Even the abandoned ideas deserve a nice place to live.</p>{empty?<div className="empty-trash"><AppIcon id="trash"/><h2>A clean slate.</h2><p>Space for whatever comes next.</p><button className="secondary-button" onClick={()=>setEmpty(false)}><RotateCcw size={14}/> Undo empty trash</button></div>:<><div className="trash-files">{['portfolio-final-FINAL-v7.fig','billion-dollar-idea.txt','new-new-website.zip'].map((s,i)=><div key={s}><AppIcon id={i===0?'papers':'writing'}/><span><b>{s}</b><small>{['Too many gradients','It was another to-do app','We’re keeping this one instead'][i]}</small></span><small>{['24 MB','2 KB','18 MB'][i]}</small></div>)}</div><button className="secondary-button" onClick={()=>setEmpty(true)}><Trash2 size={14}/> Empty trash</button><p className="muted-note">Only imaginary files will be harmed. You can undo this.</p></>}</div>}
